CREATE DATABASE ASHISH;
USE ASHISH;
/* 1 - ASHSIH
BHAVSAR */
CREATE TABLE STUDENT_RESULT
(
	STD_ID INT PRIMARY KEY,
	STD_NAME VARCHAR(20),
    STD_RESULT VARCHAR(4)
);

INSERT INTO STUDENT_RESULT (STD_ID, STD_NAME, STD_RESULT) 
VALUES (111, "JACK", "PASS"),
	(112, "ROCK", "PASS"),
    (113, "BRUCE", "FAIL"),
    (114, "SANDY", "PASS"),
    (115, "PETER", "FAIL");
/* 2 - ROSHAN
JOSHI */

ALTER TABLE STUDENT_RESULT ADD COLUMN 
STD_PERCENTAGE FLOAT AFTER STD_NAME;

UPDATE STUDENT_RESULT SET STD_PERCENTAGE = 28 WHERE STD_ID = 115;
UPDATE STUDENT_RESULT SET STD_PERCENTAGE = 80 WHERE STD_ID = 111;
UPDATE STUDENT_RESULT SET STD_PERCENTAGE = 76 WHERE STD_ID = 112;
UPDATE STUDENT_RESULT SET STD_PERCENTAGE = 33 WHERE STD_ID = 113;
UPDATE STUDENT_RESULT SET STD_PERCENTAGE = 52 WHERE STD_ID = 114;

SELECT * FROM STUDENT_RESULT WHERE STD_RESULT = "FAIL";

SELECT STD_NAME FROM STUDENT_RESULT WHERE STD_RESULT = "PASS";

SELECT * FROM STUDENT_RESULT ORDER BY STD_PERCENTAGE ASC;

SELECT * FROM STUDENT_RESULT ORDER BY STD_PERCENTAGE DESC;
	
USE ASHISH;

DELETE FROM STUDENT_RESULT WHERE STD_NAME = "SANDY";
